brand = [
  "DairyFarm",
  "GreenValley",
  "CheeseMaster",
  "FreshChoice",
  "ButterLand",
  "PureDairy",
  "YogurtValley",
  "SweetTreat",
  "Baker's Secret",
  "InstantMilk",
  "Baker's Choice",
  "CocoFarm",
  "PureGold",
  "CreamyDelight",
  "CreamyRich",
  "FarmFresh",
  "SeaHarvest",
  "MeatKing",
  "PrimeCuts",
  "OceanBounty",
  "GreenFarm",
  "VeggieDelight",
  "GreenLeaf",
  "ColorFresh",
];
category = ["Dairy", "Pantry", "Non-Veg", "Veg"];
